### ISSUE TITLE
There is a problem when training the network. Please support.

### ISSUE THREAD

**Issue by hieutv85** [MathieuCarriere/perslay#12]
Hi @MathieuCarriere 

There is still a problem when I try to run the code to train the network. Please help me. Thank you very much.  

To be more specific, I have a problem with this code line. I attached here the training error.  

Code line:
__, tr, te = evaluate_model(L,F,D,train,test,model,optimizer,loss,metrics,num_epochs=epochs,verbose=0,plots=True)_ 

Trainning error:
INFO:tensorflow:Error reported to Coordinator: in user code:

    /content/perslay.py:258 call  *
        final_representations = self.rho(concat_representations) if self.rho != "identity" else concat_representations
    /usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py:1020 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py:254 assert_input_compatibility
        ' but received input with shape ' + display_shape(x.shape))

    ValueError: Input 0 of layer sequential_5 is incompatible with the layer: expected axis -1 of input shape to have value 16039 but received input with shape (None, 439)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 346, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /content/perslay.py:258 call  *
        final_representations = self.rho(concat_representations) if self.rho != "identity" else concat_representations
    /usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py:1020 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py:254 assert_input_compatibility
        ' but received input with shape ' + display_shape(x.shape))

    ValueError: Input 0 of layer sequential_5 is incompatible with the layer: expected axis -1 of input shape to have value 16039 but received input with shape (None, 439)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-7dbdefe827e4> in <module>()
----> 1 _, tr, te = evaluate_model(L,F,D,train,test,model,optimizer,loss,metrics,num_epochs=epochs,verbose=0,plots=True)

________________________________________
10 frames
________________________________________
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    992           except Exception as e:  # pylint:disable=broad-except
    993             if hasattr(e, "ag_error_metadata"):
--> 994               raise e.ag_error_metadata.to_exception(e)
    995             else:
    996               raise

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /content/perslay.py:258 call  *
        final_representations = self.rho(concat_representations) if self.rho != "identity" else concat_representations
    /usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py:1020 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py:254 assert_input_compatibility
        ' but received input with shape ' + display_shape(x.shape))

    ValueError: Input 0 of layer sequential_5 is incompatible with the layer: expected axis -1 of input shape to have value 16039 but received input with shape (None, 439)

**Comment by hieutv85** [comment]
Hi @

**Comment by hieutv85** [comment]
Hi @MathieuCarriere, @martinroyer, @m0baxter 

Please help me to implement PERSLAY. 
When I implemented the training code line of the model, I always had an error. 
The training model code line:
**_, tr, te = evaluate_model(L,F,D,train,test,model,optimizer,loss,metrics,num_epochs=epochs,verbose=0,plots=True)**   
The error: 
ValueError: **Input 0 of layer sequential_5 is incompatible with the layer: expected axis -1 of input shape to have value 16039 but received input with shape (None, 439)** 

I attached here the error. 
I am looking forward to your reply. 

![image](https://user-images.githubusercontent.com/34276013/140596878-8f0795b1-2983-49b9-b516-9229163a6452.png)

**Comment by m0baxter** [comment]
what are you using for `L`, `F`, `D`, `train`, `test`, and `model` it looks like there are shapes in the data or in your model that are not compatible.

**Comment by hieutv85** [comment]
Hi @m0baxter ,

Thank you for your comments.
But could you please check again since I followed the Github tutorial and used the MUTAG dataset from the directory data without any modification.

The Github tutorial: https://github.com/MathieuCarriere/perslay/blob/master/tutorial/tutorialPersLay.ipynb
The MUTAG data set: https://github.com/MathieuCarriere/perslay/tree/master/tutorial/data/MUTAG/mat

I also attached here my code. I used Google Colab, version of tensorflow is 2.7.0 and sklearn is 0.22.2.post.  
Please support me. 

[TDA_Machine_Learning_PersLay.zip](https://github.com/MathieuCarriere/perslay/files/7517838/TDA_Machine_Learning_PersLay.zip)

**Comment by MathieuCarriere** [comment]
Based on the notebook you sent, it seems that you are running all cells prior to the one with `_, tr, te = evaluate_model(L,F,D,train,test,model,optimizer,loss,metrics,num_epochs=epochs,verbose=0,plots=True)`. This is not how it is supposed to be used: the cells that define the values of some `perslay_channel` keys are only when you want to define the PersLay model yourself (and in that case, you have to be careful with the dimensions, which are not consistent, and thus raising an error, when you run these cells blindly).

Try running ONLY the cell containing `model, optimizer, loss, metrics = get_model(dataset, F.shape[1])`  before the cells below the `Train the network` section, it should work.
