### ISSUE TITLE
Error when running tutorialPersLay.ipynb

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [MathieuCarriere/perslay#2]
Hi Mathieu,

I am able to run test.py but when I tried to run the tutorial. I had the following error. Do I need to update gudhi(installed from conda) to get it work?

Thanks!
Chen

 import gudhi
 print(gudhi.__version__) # 2.1.0
 generate(dataset)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-fe9f7df965eb> in <module>()
      1 import gudhi
      2 print(gudhi.__version__)
----> 3 generate(dataset)

~/Documents/osu/Research/perslay/utils.py in generate(dataset)
    242                 hks_time = float(filtration.split("-")[0])
    243                 filtration_val = _hks_signature(egvectors, egvals, time=hks_time)
--> 244                 dgmOrd0, dgmExt0, dgmRel1, dgmExt1 = _apply_graph_extended_persistence(A, filtration_val, basesimplex)
    245                 diag_file["Ord0_" + filtration].create_dataset(name=str(gid), data=dgmOrd0)
    246                 diag_file["Ext0_" + filtration].create_dataset(name=str(gid), data=dgmExt0)

~/Documents/osu/Research/perslay/utils.py in _apply_graph_extended_persistence(A, filtration_val, basesimplex)
    139                 st.assign_filtration(simplex=[vid, -2], filtration=min(fd[vid, np.where(A[vid, :] > 0)[0]]))
    140 
--> 141     st.make_filtration_non_decreasing()
    142     distorted_dgm = st.persistence()
    143     normal_dgm = dict()

AttributeError: 'gudhi.SimplexTree' object has no attribute 'make_filtration_non_decreasing'

**Comment by MathieuCarriere** [comment]
Hi Chen,
Indeed, it is better to download the source code of Gudhi and then compile it to create the python library with all functionalities. Note also that if you already have persistence diagrams, Gudhi is not necessary to run perslay.
Mathieu
