### ISSUE TITLE
Extended persistence implementation

### ISSUE THREAD

**Issue by oleg-kachan** [MathieuCarriere/perslay#4]
Dear Mathieu,

Can you give a sense of Perslay implementation of extended persistence as it differs from  Cohen-Steiner paper you cite?

You are forming the extended persistence matrix, not as block matrix of [[A, P], [0, D]], but implicitly adding dummy vertex [-2] to each vertex and edge of the graph, thus forming 1- and 2-simplices, effectively coning a graph with that dummy vertex.

Could you please tell the idea of that? What is the size of the obtained extended persistence matrix? Is it 2n x 2n or maybe 2n x 2n + 1? How do you parse "distorted diagram" variable to get Ord, Rel and Ext diagrams?

**Comment by MathieuCarriere** [comment]
Hello,

The reason we use coning is that it was proven in the Cohen-Steiner paper that the block matrix [[A,P], [0,D]] is indeed equivalent to the boundary matrix of the coned simplicial complex (see Section 6 "Algorithm", 2nd paragraph of subsection "Matrix Reduction"). We found it easier to implement coning than finding and coding the permutation P. However, both matrices should have the same size.

As for the subdiagrams Ord, Rel and Ext, we simply look at the birth and death times, and classify the points accordingly (ie Ord if both birth and death are in ascending filtration, Rel if both are in descending filtration, and Ext if birth is in ascending and death in descending).

Mathieu
