### ISSUE TITLE
error when running tutorialPersLay.ipynb

### ISSUE THREAD

**Issue by amiltonwong** [MathieuCarriere/perslay#5]
Hi, @MathieuCarriere ,

I got the following error when I execute the following line:
`diags_tmp, feats, labels = load_diagfeatlabels(dataset)`
in notebook [tutorialPersLay.ipynb](https://github.com/MathieuCarriere/perslay/blob/master/tutorial/tutorialPersLay.ipynb) .

Any hints to solve this issue?
THX!

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-6f113c568970> in <module>()
----> 1 diags_tmp, feats, labels = load_diagfeatlabels(dataset)

~/anaconda3/envs/gudhi/lib/python3.6/site-packages/perslay/experiments.py in load_diagfeatlabels(dataset, path_dataset, filtrations, verbose)
    287     # Extract and encode labels with integers
    288     L = np.array(LabelEncoder().fit_transform(np.array(feat["label"])))
--> 289     L = OneHotEncoder(sparse=False, categories="auto").fit_transform(L[:, np.newaxis])
    290 
    291     # Extract features

TypeError: __init__() got an unexpected keyword argument 'categories'
```

**Comment by MathieuCarriere** [comment]
Hi @amiltonwong 

Are you using scikit-learn >= 0.20? I think the keyword "categories" was introduced in scikit-learn 0.20, so you should probably update scikit-learn in order to make the tutorial work.

**Comment by amiltonwong** [comment]
Hi, @MathieuCarriere ,

Thanks for your reply. I've updated scikit-learn to  `0.23.1`. It works now :)
